---
# tasks file for nodejs
#
- name: Install repo of nodesource
  shell: curl --silent --location https://rpm.nodesource.com/setup_12.x | sudo bash -

- name: Installing node and npm
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - nodejs
