---
# tasks file for nodejs
#
- name: Installing node and npm
  shell: curl --silent --location https://rpm.nodesource.com/setup_12.x | sudo bash -
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - nodejs
